version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports: 
      - "27017:27017"
    volumes:
      - C:\Users\Inspiron 7568\Documents\Docker\Mongo:/data/db

